apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-deployment
  name: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpd-deployment
    spec:
      containers:
      - image: httpd:2.4
        name: httpd
        # command: ["/bin/sh","-c"]
        # args: ["apt update && apt install curl -y"]
        resources:
          limits:
            cpu: 0.6
            memory: 300Mi
          requests:
            cpu: 0.4
            memory: 200Mi
        livenessProbe: 
          httpGet: 
            path: /
            port: 80
          #initialDelaySeconds: 1
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          #initialDelaySeconds: 1
          periodSeconds: 40
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command:
            - cat
            - conf/httpd.conf
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
    
