apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy8080
  name: nginx-deploy8080
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-deploy8080
    spec:
      containers:
      - image: nginx:1.19.2
        name: nginx8080
        command: ["/bin/sh","-c"]
        args: ["sed -i 's/listen  .*/listen 8080;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 128Mi
        livenessProbe: 
          httpGet: 
            path: /
            port: 8080
          #initialDelaySeconds: 1
          periodSeconds: 120
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/
          #initialDelaySeconds: 1
          periodSeconds: 200
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
    
